### ISSUE TITLE
Documentation in README

### ISSUE THREAD

**Issue by aesedepece** [lessless/g_cloud_storage#1]
Hi @lessless ,
First of all, thanks a lot for creating this module.

Many potential users may appreciate some documentation on how to use this module.

Thanks in advance!

**Comment by lessless** [comment]
Hi Adan,
this is really unfinished toy project. But if you find it useful I can try
to give it a chance. For now, it can only list buckets inside a project.
I didn't even know whether it will pickup keys from the host project.
Let me know what functionality are you interested in and I'll try to add
it.

**Comment by aesedepece** [comment]
Hi @lessless, thanks for your prompt answer.
I need to be capable of uploading files to a bucket, which I can see is not supported yet.
I'm taking a look at your code and the Gcloud reference and maybe try to implement it on my own and then PR it to you.

**Comment by lessless** [comment]
@aesedepece Ok, I will try refactor tests with ExVCR so file upload feature will have a smoother path. 
Looks like that there should be a `Bucket.upload` method which can accept `Plug.Upload` structure https://github.com/elixir-lang/plug/blob/master/lib/plug/upload.ex and push it on a server. 
Should be pretty easy, you can ping me on #elixir-lang on slack and we work it out much faster that way.
